
#  ▄███████▄     ▄████████ ███▄▄▄▄                            
# ██▀     ▄██   ███    ███ ███▀▀▀██▄                          
#       ▄███▀   ███    █▀  ███   ███                          
#  ▀█▀▄███▀▄▄  ▄███▄▄▄     ███   ███                          
#   ▄███▀   ▀ ▀▀███▀▀▀     ███   ███                          
# ▄███▀         ███    █▄  ███   ███                          
# ███▄     ▄█   ███    ███ ███   ███                          
#  ▀████████▀   ██████████  ▀█   █▀                           
#                                                             
#  ▄█     █▄   ▄██████▄     ▄████████    ▄█   ▄█▄    ▄████████
# ███     ███ ███    ███   ███    ███   ███ ▄███▀   ███    ███
# ███     ███ ███    ███   ███    ███   ███▐██▀     ███    █▀ 
# ███     ███ ███    ███  ▄███▄▄▄▄██▀  ▄█████▀      ███       
# ███     ███ ███    ███ ▀▀███▀▀▀▀▀   ▀▀█████▄    ▀███████████
# ███     ███ ███    ███ ▀███████████   ███▐██▄            ███
# ███ ▄█▄ ███ ███    ███   ███    ███   ███ ▀███▄    ▄█    ███
#  ▀███▀███▀   ▀██████▀    ███    ███   ███   ▀█▀  ▄████████▀ 
#                          ███    ███   ▀                     
#
#                 https://github.com/kbuckleys/

[mgr]
show_hidden = true
show_symlink = true
sort_sensitive = false
sort_reverse = false
show_icons = true
linemode = "size"

system_default = [{ run = "yazi \"$1\"", desc = "Yazi (Default)", for = "linux" }]

[open]
rules = [
    { name = "*/", use = ["reveal"] },
    { name = "*", use = ["open", "edit", "reveal"] },
    { mime = "image/*", use = ["open", "reveal"] },
    { mime = "video/*", use = ["open", "reveal"] },
    { mime = "audio/*", use = ["open", "reveal"] },
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = ["extract", "view_archive", "reveal"] },
    { mime = "application/pdf", use = ["open", "reveal"] },
    { mime = "application/epub+zip", use = ["open", "reveal"] },
]

[opener]
open = [{ run = 'xdg-open "$@"', desc = "Open", for = "unix" },]
edit = [{ run = 'kitty -e nvim "$@"', orphan = true, desc = "Edit", for = "unix" }]
reveal = [{ run = 'thunar "$1"', desc = "Reveal", for = "unix" },]
extract = [{ run = '7z x "$1"', block = true, desc = "Extract with 7z", for = "unix" },]
view_archive = [{ run = 'if [ -f "$1" ]; then case "$1" in *.tar) tar tf "$1" ;; *.zip) unzip -l "$1" ;; *.rar) unrar l "$1" ;; *.7z) 7z l "$1" ;; esac; echo "Press enter to exit"; read _; fi', block = true, desc = "View archive contents", for = "unix" },]
