# ┌─┐┌─┐┌┐┌┬ ┬┌─┐┬─┐┬┌─┌─┐
# ┌─┘├┤ │││││││ │├┬┘├┴┐└─┐
# └─┘└─┘┘└┘└┴┘└─┘┴└─┴ ┴└─┘
# https://github.com/kbuckleys/

# If the user's terminal is in dark mode, Yazi will load `theme-dark.toml` on startup; otherwise, `theme-light.toml`.
# You can override any parts of them that are not related to the dark/light mode in your own `theme.toml`.

# If you want to dynamically override their content based on dark/light mode, you can specify two different flavors
# for dark and light modes under `[flavor]`, and do so in those flavors instead.

"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[app]
overall = {}

[mgr]
cwd = { fg = "#9bbfbf" }
find_keyword = { fg = "#e0d8a4", bold = true, italic = true }
find_position = { fg = "#c8a4e0", bg = "reset", bold = true, italic = true }
marker_selected = { bg = "#e0d8a4" }
marker_copied = { bg = "#b6e0a4" }
marker_marked = { bg = "#c8a4e0" }
marker_cut = { bg = "#E0AEA4" }
count_copied = { fg = "#000000", bg = "#b6e0a4" }
count_cut = { fg = "#000000", bg = "#E0AEA4" }
count_selected = { fg = "#000000", bg = "#e0d8a4" }
border_style = { fg = "#000000" }

[tabs]
active = { bg = "#9bbfbf", fg = "#000000", bold = true }
inactive = { fg = "#9bbfbf", bg = "#000000" }
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[mode]
normal_main = { bg = "#9bbfbf", fg = "#000000", bold = true }
normal_alt = { fg = "#9bbfbf", bg = "#000000" }
select_main = { bg = "#c8a4e0", fg = "#000000", bold = true }
select_alt = { fg = "#c8a4e0", bg = "#000000" }
unset_main = { bg = "#e0d8a4", bold = true }
unset_alt = { fg = "#e0d8a4", bg = "#000000" }

[indicator]
preview = { underline = false }
padding = { open = "█", close = "█" }

[status]
overall = {}
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Permissions
perm_sep = { fg = "#20242a" }
perm_type = { fg = "#b6e0a4" }
perm_read = { fg = "#e0d8a4" }
perm_write = { fg = "#E0AEA4" }
perm_exec = { fg = "#9bbfbf" }

# Progress
progress_normal = { fg = "#fab387", bg = "#20242a" }
progress_error = { fg = "#E0AEA4", bg = "#20242a" }

[which]
cols = 3
mask = { bg = "#20242a" }
cand = { fg = "#e0d8a4" }
rest = { fg = "#20242a" }
desc = { fg = "#dfdfdd" }
separator = "  "
separator_style = { fg = "#5a6069" }

[confirm]
border = { fg = "#E0AEA4" }
title = { fg = "#E0AEA4", bold = true }
body = {}
list = {}
btn_yes = {}
btn_no = {}
btn_labels = [ "[Y]ES", "[N]O" ]

[spot]
border = { fg = "#9bbfbf" }
title = { fg = "#9bbfbf", bold = true }
tbl_col = { fg = "#9bbfbf" }
tbl_cell = { fg = "#dfdfdd", bg = "#20242a" }

[notify]
title_info = { fg = "#b6e0a4" }
title_warn = { fg = "#e0d8a4" }
title_error = { fg = "#E0AEA4" }
icon_info = ""
icon_warn = ""
icon_error = ""

[pick]
border = { fg = "#9bbfbf" }
active = { fg = "#c8a4e0", bold = true }
inactive = {}

[input]
border = { fg = "#9bbfbf" }
title = { bold = true }
value = { fg = "#9bbfbf" }
selected = { reversed = true }

[cmp]
border = { fg = "#9bbfbf" }
active = { fg = "#000000", bg = "#9bbfbf" }
inactive = { fg = "#9bbfbf" }
icon_file = ""
icon_folder = ""
icon_command = ""

[tasks]
border = { fg = "#9bbfbf" }
title = { bold = true }
hovered = { fg = "#dfdfdd", bg = "#20242a" }

[help]
on = {}
run = {}
desc = {}
hovered = { reversed = true }
footer = { fg = "#dfdfdd", bg = "#20242a" }

[filetype]
rules = [
	# Image
	{ mime = "image/*", fg = "#b6e0a4" },
	# Media
	{ mime = "{audio,video}/*", fg = "#c8a4e0" },
	# Archive
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#fab387" },
	# Document
	{ mime = "application/{pdf,doc,rtf}", fg = "#9bbfbf" },
	# Virtual file system
	{ mime = "vfs/{absent,stale}", fg = "#a0a09b" },
	# Special file
  { mime = "inode/empty", fg = "#a0a09b" },

  # Orphan (broken) symlinks first
  { url = "*", is = "orphan", fg = "#E0AEA4" },

  # Valid symlinks last (won't override orphans)
  { url = "*", is = "link", fg = "#e0d8a4" },
	{ url = "*", is = "exec", fg = "#b6e0a4" },

	# Dummy file
	{ url = "*", is = "dummy", bg = "#fab387", fg = "#000000" },
	{ url = "*/", is = "dummy", bg = "#fab387", fg = "#000000" },
	# Fallback
	{ url = "*/", fg = "#9bbfbf" }
]
