# ┌─┐┌─┐┌┐┌┬ ┬┌─┐┬─┐┬┌─┌─┐
# ┌─┘├┤ │││││││ │├┬┘├┴┐└─┐
# └─┘└─┘┘└┘└┴┘└─┘┴└─┴ ┴└─┘
# https://github.com/kbuckleys/

[mgr]
cwd = { fg = "#9bbfbf", bold = true }
find_keyword = { fg = "#e0d8a4", bg = "#000000" }
marker_copied = { fg = "#000000", bg = "#C5E1A5" }
marker_cut = { fg = "#000000", bg = "#E0A4A4" }
marker_marked = { fg = "#000000", bg = "#BCA4E0" }
marker_selected = { fg = "#000000", bg = "#E0DEA4" }
count_copied = { fg = "#c5e1a5", bold = true, reversed = true }
count_cut = { fg = "#E0A4A4", bold = true, reversed = true }
count_selected = { fg = "#BCA4E0", bold = true, reversed = true }
border_style = { fg = "#000000" }

[indicator]
preview = { underline = false }

[tabs]
active = { fg = "#000000", bg = "#9BBFBF", bold = true }
inactive = { fg = "#9BBFBF", bg = "#000000" }
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[mode]
normal_main = { fg = "#000000", bg = "#9BBFBF", bold = true }
normal_alt = { fg = "#9BBFBF", bg = "#000000" }

select_main = { fg = "#000000", bg = "#BCA4E0", bold = true }
select_alt = { fg = "#BCA4E0", bg = "#000000" }

unset_main = { fg = "#000000", bg = "#E0DEA4", bold = true }
unset_alt = { fg = "#E0DEA4", bg = "#000000" }

[status]
overall = { fg = "#9BBFBF" }
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Permissions
perm_type = { fg = "#BCA4E0" }
perm_read = { fg = "#E0DEA4" }
perm_write = { fg = "#E0A4A4" }
perm_exec = { fg = "#c5e1a5" }
perm_sep = { fg = "#9bbfbf" }

# Progress
progress_normal = { fg = "#fab387", bg = "#20242a" }
progress_error = { fg = "#e0aea4", bg = "#20242a" }

[which]
cols = 3
mask = { bg = "#20242a" }
cand = { fg = "#e0d8a4", bold = true }
rest = { fg = "#c8a4e0", italic = true }
desc = { fg = "#dfdfdd" }

[confirm]
border = { fg = "#E0A4A4" }
title = { fg = "#E0A4A4", bold = true }
content = { fg = "#DFDFDD", bold = true }
list = { fg = "#CECDC3" }
btn_yes = { fg = "#DFDFDD", bg = "#000000"}
btn_no = { fg = "#CECDC3", bg = "#000000", bold = true }

[spot]
border = { fg = "#9BBFBF" }
title = { fg = "#9BBFBF", bold = true }
tbl_col = { fg = "#dfdfdd" }
tbl_cell = { bg = "#20242a" }

[notify]
title_info = { fg = "#C5E1A5" }
title_warn = { fg = "#E0DEA4" }
title_error = { fg = "#E0A4A4" }

[input]
border = { fg = "#9BBFBF" }
title = { fg = "#9BBFBF", bold = true }
value = { fg = "#DFDFDD" }
selected = { bg = "#9BBFBF" }

[cmp]
border = { fg = "#9BBFBF", bold = true }
active = { fg = "#000000", bg = "#9BBFBF" }
inactive = { fg = "#9BBFBF" }

[tasks]
border = { fg = "#9BBFBF" }
title = { fg = "#9BBFBF", bold = true }
hovered = { bg = "#56606D" }

[help]
on = { fg = "#E0DEA4" }
run = { fg = "#C5E1A5" }
desc = { fg = "#DFDFDD", italic = true }
hovered = { bg = "#20242a" }
footer = { fg = "#dfdfdd", bg = "#20242a" }

[filetype]
rules = [
  # Images
  { mime = "image/*", fg = "#DFDFDD" },

  # Media
  { mime = "video/*", fg = "#DFDFDD" },
  { mime = "audio/*", fg = "#DFDFDD" },

  # Broken symbolic link
  { name = "*", is = "orphan", fg = "#E0A4A4" },
  { name = "*/", is = "orphan", fg = "#E0A4A4" },

  # Symbolic links
  { name = "*", is = "link", fg = "#BCA4E0" },
  { name = "*/", is = "link", fg = "#BCA4E0" },

  # Executable
  { name = "*", is = "exec", fg = "#E0DEA4" },

  # Empty files
  { mime = "inode/empty", fg = "#56606d" },

  # Fallback
  { name = "*", fg = "#DFDFDD" },
  { name = "*/", fg = "#9BBFBF" }
]
