# ┌─┐┌─┐┌┐┌┬ ┬┌─┐┬─┐┬┌─┌─┐
# ┌─┘├┤ │││││││ │├┬┘├┴┐└─┐
# └─┘└─┘┘└┘└┴┘└─┘┴└─┴ ┴└─┘
# https://github.com/kbuckleys/

"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[app]
overall = {}

[mgr]
cwd = { fg = "#9bbfbf" }
find_keyword = { bold = true, underline = true }
find_position = { bg = "#000000", bold = true }
marker_selected = { bg = "#e0d8a4" }
marker_copied = { bg = "#b6e0a4" }
marker_marked = { bg = "#c8a4e0" }
marker_cut = { bg = "#e78284" }
count_copied = { fg = "#000000", bg = "#b6e0a4" }
count_cut = { fg = "#000000", bg = "#e78284" }
count_selected = { fg = "#000000", bg = "#e0d8a4" }
border_style = { fg = "#000000" }

[tabs]
active = { bg = "#9bbfbf", fg = "#000000" }
inactive = { bg = "#000000", fg = "#9bbfbf" }
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[mode]
normal_main = { bg = "#9bbfbf", fg = "#000000", bold = true }
normal_alt = { fg = "#9bbfbf", bg = "#20242a" }
select_main = { bg = "#c8a4e0", fg = "#000000", bold = true }
select_alt = { fg = "#c8a4e0", bg = "#20242a" }
unset_main = { bg = "#e0d8a4", fg = "#000000", bold = true }
unset_alt = { fg = "#e0d8a4", bg = "#20242a" }

[indicator]
preview = { underline = false }
padding = { open = "█", close = "█" }

[status]
overall = { fg = "#9bbfbf" }
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Permissions
perm_sep = { fg = "#20242a" }
perm_type = { fg = "#b6e0a4" }
perm_read = { fg = "#e0d8a4" }
perm_write = { fg = "#e78284" }
perm_exec = { fg = "#9bbfbf" }

# Progress
progress_normal = { fg = "#fab387", bg = "#20242a" }
progress_error = { fg = "#e78284", bg = "#20242a" }

[which]
cols = 3
mask = { bg = "#20242a" }
cand = { fg = "#fab387" }
rest = { fg = "#20242a" }
desc = { fg = "#dfdfdd" }
separator = "  "
separator_style = { fg = "#5a6069" }

[confirm]
border = { fg = "#e78284" }
title = { fg = "#eebebe", bold = true }
body = {}
list = {}
btn_yes = { fg = "#eebebe" }
btn_no = { fg = "#eebebe" }
btn_labels = [ "[Y]ES", "[N]O" ]

[spot]
border = { fg = "#9bbfbf" }
title = { fg = "#9bbfbf", bold = true }
tbl_col = { fg = "#9bbfbf" }
tbl_cell = { fg = "#9bbfbf", bg = "#20242a" }

[notify]
title_info = { fg = "#b6e0a4" }
title_warn = { fg = "#e0d8a4" }
title_error = { fg = "#eebebe" }
icon_info = ""
icon_warn = ""
icon_error = ""

[pick]
border = { fg = "#9bbfbf" }
active = { fg = "#c8a4e0", bold = true }
inactive = {}

[input]
border = { fg = "#fab387" }
title = { bold = true }
value = { fg = "#fab387" }
selected = { reversed = true }

[cmp]
border = { fg = "#fab387" }
active = { fg = "#000000", bg = "#fab387" }
inactive = { fg = "#fab387" }

[tasks]
border = { fg = "#fab387" }
title = { bold = true }
hovered = { fg = "#dfdfdd", bg = "#20242a" }

[help]
on = {}
run = {}
desc = {}
hovered = { reversed = true }
footer = { fg = "#dfdfdd", bg = "#20242a" }

[filetype]
rules = [
	# Image
	{ mime = "image/*", fg = "#b6e0a4" },

	# Media
	{ mime = "{audio,video}/*", fg = "#e0d8a4" },

	# Archive
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#fab387" },

	# Document
	{ mime = "application/{pdf,doc,rtf}", fg = "#9bbfbf" },

	# Virtual file system
	{ mime = "vfs/{absent,stale}", fg = "#a0a09b" },

	# Special file
  { mime = "inode/empty", fg = "#a0a09b" },

  # Orphan (broken) symlinks first
  { url = "*", is = "orphan", fg = "#e78284" },

  # Valid symlinks last (won't override orphans)
  { url = "*", is = "link", fg = "#c8a4e0" },
	{ url = "*", is = "exec", fg = "#fab387" },

	# Dummy file
	{ url = "*", is = "dummy", bg = "#fab387", fg = "#000000" },
	{ url = "*/", is = "dummy", bg = "#fab387", fg = "#000000" },

	# Fallback
	{ url = "*/", fg = "#9bbfbf" },
]

[icon]
dirs = [
	{ name = ".git", text = "" },
	{ name = ".npm", text = "" },
  { name = ".steam", text = "" },
  { name = ".cache", text = "" },
  { name = ".local", text = "" },
  { name = ".cargo", text = "󱣘" },
  { name = ".github", text = "" },
  { name = ".config", text = "" },
  { name = ".mozilla", text = "" },
  { name = "scripts", text = "󰑷" },
	{ name = "Desktop", text = "" },
	{ name = "Development", text = "" },
	{ name = "Documents", text = "" },
	{ name = "Downloads", text = "󰃘" },
	{ name = "Library", text = "" },
	{ name = "Movies", text = "" },
	{ name = "Music", text = "" },
	{ name = "Pictures", text = "" },
	{ name = "Public", text = "" },
	{ name = "Videos", text = "" }
]
conds = [
	{ if = "orphan", text = "" },
	{ if = "link", text = "" },
	{ if = "block", text = "" },
	{ if = "char", text = "" },
	{ if = "fifo", text = "" },
	{ if = "sock", text = "" },
	{ if = "sticky", text = "" },
	{ if = "dummy", text = "" },
	{ if = "dir", text = "" },
	{ if = "exec", text = "" },
	{ if = "!dir", text = "" }
]
exts = [
  { name = "sh", text = "󰑷" },
  { name = "doc", text = "" },
  { name = "docx", text = "" },
  { name = "odt", text = "" },
  { name = "wpd", text = "" },
  { name = "pdf", text = "" },

  { name = "z", text = "" },
  { name = "zip", text = "" },
  { name = "deb", text = "" },
  { name = "pkg", text = "" },
  { name = "rpm", text = "" },
  { name = "gz", text = "" },
  { name = "tar", text = "" },
  { name = "rar", text = "" },
  { name = "7z", text = "" },
  { name = "gzip", text = "" },
  { name = "xz", text = "" },
  { name = "zstd", text = "" },
  { name = "bzip", text = "" },
  { name = "lzma", text = "" },
  { name = "lzma", text = "" },
  { name = "compress", text = "" },
  { name = "archive", text = "" },
  { name = "cpio", text = "" },
  { name = "arj", text = "" },
  { name = "xar", text = "" },
  { name = "cab", text = "" },

  { name = "bin", text = "" },
  { name = "dmg", text = "" },
  { name = "iso", text = "" },
  { name = "toast", text = "" },
  { name = "vcd", text = "" },

  { name = "mp4", text = "" },
  { name = "mkv", text = "" },
  { name = "webm", text = "" },
  { name = "3g2", text = "" },
  { name = "3gp", text = "" },
  { name = "avi", text = "" },
  { name = "flv", text = "" },
  { name = "h264", text = "" },
  { name = "m4v", text = "" },
  { name = "mov", text = "" },
  { name = "mpg", text = "" },
  { name = "mpeg", text = "" },
  { name = "rm", text = "" },
  { name = "swf", text = "" },
  { name = "vob", text = "" },
  { name = "wmv", text = "" },

  { name = "srt", text = "" },
  { name = "vtt", text = "" },
  { name = "ass", text = "" },
  { name = "ssa", text = "" },
  { name = "sub", text = "" },
  { name = "idx", text = "" },

  { name = "mp3", text = "󰎅" },
  { name = "wav", text = "󰎅" },

  { name = "key", text = "󰐩" },
  { name = "odp", text = "󰐩" },
  { name = "pps", text = "󰐩" },
  { name = "ppt", text = "󰐩" },
  { name = "pptx", text = "󰐩" },

  { name = "apk", text = "󰓷" },
  { name = "c", text = "" },
  { name = "class", text = "" },
  { name = "cpp", text = "" },
  { name = "cs", text = "" },
  { name = "h", text = "" },
  { name = "jar", text = "" },
  { name = "java", text = "" },
  { name = "swift", text = "" },
  { name = "vb", text = "" },

  { name = "ods", text = "" },
  { name = "xls", text = "" },
  { name = "xlsm", text = "" },
  { name = "xlsx", text = "" },

  { name = "ai", text = "" },
  { name = "ps", text = "" },
  { name = "psd", text = "" },
  { name = "tif", text = "" },
  { name = "tiff", text = "" },
  { name = "bmp", text = "" },
  { name = "ico", text = "" },
  { name = "webp", text = "" },
  { name = "png", text = "" },
  { name = "jpg", text = "" },
  { name = "jpeg", text = "" },
  { name = "gif", text = "" },

  { name = "asp", text = "" },
  { name = "aspx", text = "" },
  { name = "cfm", text = "" },
  { name = "cgi", text = "" },
  { name = "pl", text = "" },
  { name = "css", text = "" },
  { name = "htm", text = "" },
  { name = "html", text = "" },
  { name = "xhtml", text = "" },
  { name = "js", text = "" },
  { name = "jsp", text = "" },
  { name = "part", text = "" },
  { name = "php", text = "" },
  { name = "py", text = "󰌠" },
  { name = "rss", text = "" },

  { name = "csv", text = "" },
  { name = "log", text = "" },
  { name = "sav", text = "" },

  { name = "email", text = "󰇮" },
  { name = "eml", text = "󰇮" },
  { name = "emlx", text = "󰇮" },
  { name = "msg", text = "󰇮" },
  { name = "oft", text = "󰇮" },
  { name = "ost", text = "󰇮" },
  { name = "pst", text = "󰇮" },
  { name = "vcf", text = "󰇮" },

  { name = "fnt", text = "" },
  { name = "fon", text = "" },
  { name = "otf", text = "" },
  { name = "ttf", text = "" },
]
