# ┌─┐┌─┐┌┐┌┬ ┬┌─┐┬─┐┬┌─┌─┐
# ┌─┘├┤ │││││││ │├┬┘├┴┐└─┐
# └─┘└─┘┘└┘└┴┘└─┘┴└─┴ ┴└─┘
# https://github.com/kbuckleys/

[mgr]
show_symlink = true
show_hidden = true
linemode = "size"

[opener]
open = [
  { run = 'xdg-open "$@" & disown' },
]
wine_exe = [
  { run = 'wine "$1" & disown', desc = "Wine" }
]

[open]
rules = [
  { url = "*.exe", use = ["wine_exe"] },
]

edit = [
  { run = 'footclient nvim "$@" & disown', desc = "Open in Neovim" }
]
