# ┌─┐┌─┐┌┐┌┬ ┬┌─┐┬─┐┬┌─┌─┐
# ┌─┘├┤ │││││││ │├┬┘├┴┐└─┐
# └─┘└─┘┘└┘└┴┘└─┘┴└─┴ ┴└─┘
# https://github.com/kbuckleys/

[mgr]
sort_sensitive = false
sort_reverse = false
show_symlink = true
show_hidden = true
show_icons = true
linemode = "size"

system_default = [{ run = "yazi \"$1\"", desc = "Yazi (Default)", for = "linux" }]

[open]
rules = [
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = ["extract", "view_archive"] },
    { mime = "application/epub+zip", use = ["open"] },
    { mime = "application/pdf", use = ["open"] },
    { name = "*", use = ["open", "edit"]},
    { mime = "image/*", use = ["open"]},
    { mime = "video/*", use = ["open"]},
    { mime = "audio/*", use = ["open"]},
]

[opener]
view_archive = [{ run = 'if [ -f "$1" ]; then case "$1" in *.tar) tar tf "$1" ;; *.zip) unzip -l "$1" ;; *.rar) unrar l "$1" ;; *.7z) 7z l "$1" ;; esac; echo "Press enter to exit"; read _; fi', block = true, desc = "View archive contents", for = "unix" },]
edit = [{ run = 'footclient -e nvim "$@"', orphan = true, desc = "Edit with Nvim", for = "unix" }]
extract = [{ run = '7z x "$1"', block = true, desc = "Extract with 7z", for = "unix" },]
open = [{ run = 'xdg-open "$@"', desc = "Open", for = "unix" },]
