# ┌─┐┌─┐┌┐┌┬ ┬┌─┐┬─┐┬┌─┌─┐
# ┌─┘├┤ │││││││ │├┬┘├┴┐└─┐
# └─┘└─┘┘└┘└┴┘└─┘┴└─┴ ┴└─┘
# https://github.com/kbuckleys/

[mgr]
show_symlink = true
show_hidden = true
linemode = "size"

[opener]
open = [{ run = 'xdg-open "$@" & disown' }]
edit = [{ run = 'footclient nvim "$@" & disown', desc = "Open in Neovim" }]
